### ISSUE TITLE
Provisioned persistent volume stays attached when underlying node is deprovisioned preventing relocation to another node

### ISSUE THREAD

**Issue by gnadaban** [kubernetes-sigs/azuredisk-csi-driver#1301]
**What happened**:

Node on which a PVC was provisioned was deleted. PV stays assigned to missing node and never gets detached.

Status of VolumeAttachment shows detach error:

```
status:
  attached: true
  attachmentMetadata:
    LUN: "0"
  detachError:
    message: csinode.storage.k8s.io "<redacted>" not found
```

**What you expected to happen**:

When a Kubernetes node is deprovisioned, volume attachments should be detached, so that the Pod and the corresponding PVC can be bound to another existing node.

**How to reproduce it**:

Create a Pod with a PVC, wait for it to be provisioned, then delete the node as done by eg. autoscaler.

**Anything else we need to know?**:

**Environment**:
- CSI Driver version: `1.16`
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:30:48Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:32:02Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by andyzhangx** [comment]
if a Kubernetes node is deleted, the pod with disk pv would be rescheduled to a new node, and then detach disk would happen. Do you know whether that the pod is scheduled to the new node?

**Comment by gnadaban** [comment]
The Pod cannot be rescheduled because the volume stays attached, and it is never detached.

**Comment by andyzhangx** [comment]
and what if you delete that pod by force?

**Comment by gnadaban** [comment]
The Pod would stay in Init forever as it's rescheduled to another node, but the volume is never attached as it stays attached.
Deleting the Pod doesn't help either.

**Comment by gnadaban** [comment]
For example a VolumeAttachment failing to detach has this error:

```
status:
  attached: true
  attachmentMetadata:
    LUN: "0"
  detachError:
    message: 'rpc error: code = Internal desc = Could not detach volume /subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/pvc-009d4582-3305-453e-9fb1-5738dfe22b63
      from node <redacted>: failed to get azure instance id for node
      "<redacted>": not a vmss instance'
```

Note: the cluster is provisioned using `cluster-api` and has MachineDeployments instead of VMSS nodes.

**Comment by andyzhangx** [comment]
@gnadaban what's the `disable-avset-nodes` value of your disk driver controller? set as `--disable-avset-nodes=false` (by default) should fix the `get azure instance id for node` error and unblock disk detach:

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/62cbae04087080827fe8159461299c31bdfaf58d/deploy/csi-azuredisk-controller.yaml#L143

**Comment by andyzhangx** [comment]
try run `kubectl describe pod csi-azuredisk-controller-xxx -n kube-system` to check `disable-avset-nodes` setting.

**Comment by gnadaban** [comment]
Hi @andyzhangx , I'll test that setting as soon as I can. 

Since the volumes are stuck I had to remove them manually in the Azure portal, but the corresponding Kubernetes resources are not being cleaned up. Is there any cleanup-loop in the CSI controller that will eventually take care of these?

If not, how can I delete them safely?

**Comment by andyzhangx** [comment]
> Hi @andyzhangx , I'll test that setting as soon as I can.
> 
> Since the volumes are stuck I had to remove them manually in the Azure portal, but the corresponding Kubernetes resources are not being cleaned up. Is there any cleanup-loop in the CSI controller that will eventually take care of these?
> 
> If not, how can I delete them safely?

@gnadaban the pv could not be deleted since the pod using that pv is still not deleted, as long as you delete the pods, the k8s pv resources could be deleted automatically.

**Comment by gnadaban** [comment]
@andyzhangx Pods that originally had the volumes are long gone and we still see PVs that arent' released.
What now?

**Comment by andyzhangx** [comment]
> @andyzhangx Pods that originally had the volumes are long gone and we still see PVs that arent' released. What now?

@gnadaban could you paste the PVC, PV status? You could delete PVC to clean up the underlying disk.

**Comment by gnadaban** [comment]
Issue still stands, the `azuredisk` controller logs show the PVs cannot be removed:

```
E0504 00:02:30.842553       1 utils.go:82] GRPC error: rpc error: code = Internal desc = Could not detach volume /subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/pvc-798ef09d-88b8-4549-acf1-6b9654eb808b from node alcyone-worker-zone-3-fc8bg: failed to get azure instance id for node "<redacted>": not a vmss instance
```

Note: Force-deleting the PVs don't make a difference.

**Comment by andyzhangx** [comment]
can you run `kubectl edit deployment csi-azuredisk-controller -n kube-system`, and set `--disable-avset-nodes=false`:

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/62cbae04087080827fe8159461299c31bdfaf58d/deploy/csi-azuredisk-controller.yaml#L143

also could you share the init logs of azuredisk controller, thanks.

**Comment by gnadaban** [comment]
> Hi @andyzhangx , the controller is deployed via the Helm chart with `disableAvailabilitySetNodes=true`. Even with that the deployment doesn't have the `--disable-avset-nodes` flag passed in.
> 
> Since we talked I restarted the deployment so I no longer have the logs with the errors, sry.

Correction: I DO see the `--disable-avset-nodes=true` passed in to the controller.

**Comment by gnadaban** [comment]
I've updated to 1.18 and flipped that flag to false as I'm getting errors in the controller like this:

```
I0505 18:30:01.585716       1 controllerserver.go:376] Trying to attach volume /subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/pvc-17340611-6472-437e-9d78-eac68ebc9448 to node <redacted>
I0505 18:30:01.585728       1 azure_vmss_cache.go:320] Assuming node "<redacted>" is managed by VMSS since DisableAvailabilitySetNodes is set to true
E0505 18:30:01.585733       1 azure_controller_common.go:466] error of getting data disks for node <redacted>: not a vmss instance
```

**Comment by gnadaban** [comment]
With the `disableAvailabilitySetNodes=true` and 1.17 chart/controller it appears this flag is not working as it's still attempting to treat nodes as VMSS instance:

```
I0505 18:40:53.889640       1 controllerserver.go:439] Trying to detach volume /subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/pvc-9b0c0f9a-5501-4292-9e5e-902b06f0a587 from node <redacted>
I0505 18:40:53.889660       1 azure_vmss_cache.go:320] Assuming node "<redacted>" is managed by VMSS since DisableAvailabilitySetNodes is set to true
E0505 18:40:53.889670       1 azure_vmss.go:367] Unable to find node <redacted>: not a vmss instance
```

Using `disableAvailabilitySetNodes=false` yields similar results.

**Comment by andyzhangx** [comment]
> With the `disableAvailabilitySetNodes=true` and 1.17 chart/controller it appears this flag is not working as it's still attempting to treat nodes as VMSS instance:
> 
> ```
> I0505 18:40:53.889640       1 controllerserver.go:439] Trying to detach volume /subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/pvc-9b0c0f9a-5501-4292-9e5e-902b06f0a587 from node <redacted>
> I0505 18:40:53.889660       1 azure_vmss_cache.go:320] Assuming node "<redacted>" is managed by VMSS since DisableAvailabilitySetNodes is set to true
> E0505 18:40:53.889670       1 azure_vmss.go:367] Unable to find node <redacted>: not a vmss instance
> ```
> 
> Using `disableAvailabilitySetNodes=false` yields similar results.

@gnadaban what's the initialization logs of disk driver controller pod logs? after changing the `disableAvailabilitySetNodes` setting, you need to delete all existing running deployment pods, otherwise pod with old config may still be running.

**Comment by gnadaban** [comment]
Hi @andyzhangx , I tested deployment and deletion of a new Redis which has PVCs with 1.17 and  `disableAvailabilitySetNodes=false` and it appears to work.

However, deleting unused PVCs created before and deleting their PVs seems to fail still and the PVs got stuck in `Terminating` status.

Attempting to delete these previously created PVs has errors in the controller log:

```
controllerserver.go:439] Trying to detach volume /subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/pvc-8019153c-6d7a-46b1-a935-5ad157492d56 from node <redacted>
azure_vmss_cache.go:332] Node <redacted> has joined the cluster since the last VM cache refresh, refreshing the cache
azure_backoff.go:101] VirtualMachinesClient.List(<redacted>) success
azure_vmss.go:367] Unable to find node <redacted>: not a vmss instance
azure_controller_common.go:319] failed to get azure instance id (not a vmss instance)
azure_metrics.go:112] "Observed Request Latency" latency_seconds=0.09292251 request="azuredisk_csi_driver_controller_unpublish_volume" resource_group="<redacted>" subscription_id="<redacted>" source="disk.csi.azure.com" volumeid="/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/pvc-8019153c-6d7a-46b1-a935-5ad157492d56" node="<redacted>" result_code="failed"
utils.go:82] GRPC error: rpc error: code = Internal desc = Could not detach volume /subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/pvc-8019153c-6d7a-46b1-a935-5ad157492d56 from node <redacted>: failed to get azure instance id for node "<redacted>": not a vmss instance
utils.go:77] GRPC call: /csi.v1.Controller/ControllerUnpublishVolume
utils.go:78] GRPC request: {"node_id":"<redacted>","volume_id":"/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/pvc-9b0c0f9a-5501-4292-9e5e-902b06f0a587"}
controllerserver.go:439] Trying to detach volume /subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/pvc-9b0c0f9a-5501-4292-9e5e-902b06f0a587 from node <redacted>
azure_vmss_cache.go:332] Node <redacted> has joined the cluster since the last VM cache refresh, refreshing the cache
azure_backoff.go:101] VirtualMachinesClient.List(<redacted>) success
azure_vmss.go:367] Unable to find node <redacted>: not a vmss instance
azure_controller_common.go:319] failed to get azure instance id (not a vmss instance)
azure_metrics.go:112] "Observed Request Latency" latency_seconds=0.090153146 request="azuredisk_csi_driver_controller_unpublish_volume" resource_group="<redacted>" subscription_id="<redacted>" source="disk.csi.azure.com" volumeid="/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/pvc-9b0c0f9a-5501-4292-9e5e-902b06f0a587" node="<redacted>" result_code="failed"
utils.go:82] GRPC error: rpc error: code = Internal desc = Could not detach volume /subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/pvc-9b0c0f9a-5501-4292-9e5e-902b06f0a587 from node <redacted>: failed to get azure instance id for node "<redacted>": not a vmss instance
utils.go:77] GRPC call: /csi.v1.Controller/ControllerUnpublishVolume
utils.go:77] GRPC call: /csi.v1.Controller/ControllerUnpublishVolume
utils.go:78] GRPC request: {"node_id":"<redacted>","volume_id":"/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/pvc-8019153c-6d7a-46b1-a935-5ad157492d56"}
utils.go:78] GRPC request: {"node_id":"<redacted>","volume_id":"/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/pvc-9b0c0f9a-5501-4292-9e5e-902b06f0a587"}
controllerserver.go:439] Trying to detach volume /subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/pvc-8019153c-6d7a-46b1-a935-5ad157492d56 from node <redacted>
controllerserver.go:439] Trying to detach volume /subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/pvc-9b0c0f9a-5501-4292-9e5e-902b06f0a587 from node <redacted>
azure_vmss_cache.go:332] Node <redacted> has joined the cluster since the last VM cache refresh, refreshing the cache
azure_vmss_cache.go:332] Node <redacted> has joined the cluster since the last VM cache refresh, refreshing the cache
azure_backoff.go:101] VirtualMachinesClient.List(<redacted>) success
azure_vmss.go:367] Unable to find node <redacted>: not a vmss instance
azure_controller_common.go:319] failed to get azure instance id (not a vmss instance)
azure_metrics.go:112] "Observed Request Latency" latency_seconds=0.083828821 request="azuredisk_csi_driver_controller_unpublish_volume" resource_group="<redacted>" subscription_id="<redacted>" source="disk.csi.azure.com" volumeid="/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/pvc-8019153c-6d7a-46b1-a935-5ad157492d56" node="<redacted>" result_code="failed"
utils.go:82] GRPC error: rpc error: code = Internal desc = Could not detach volume /subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/pvc-8019153c-6d7a-46b1-a935-5ad157492d56 from node <redacted>: failed to get azure instance id for node "<redacted>": not a vmss instance
azure_backoff.go:101] VirtualMachinesClient.List(<redacted>) success
azure_vmss.go:367] Unable to find node <redacted>: not a vmss instance
azure_controller_common.go:319] failed to get azure instance id (not a vmss instance)
azure_metrics.go:112] "Observed Request Latency" latency_seconds=0.145617125 request="azuredisk_csi_driver_controller_unpublish_volume" resource_group="<redacted>" subscription_id="<redacted>" source="disk.csi.azure.com" volumeid="/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/pvc-9b0c0f9a-5501-4292-9e5e-902b06f0a587" node="<redacted>" result_code="failed"
utils.go:82] GRPC error: rpc error: code = Internal desc = Could not detach volume /subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/pvc-9b0c0f9a-5501-4292-9e5e-902b06f0a587 from node <redacted>: failed to get azure instance id for node "<redacted>": not a vmss instance
```

It's like the controller correctly detects that the node the PVs are on are NOT VMSS, but then still fails to detach attempting it as if it were. I'm confused.

I saw this in the controller init logs:
```
W0505 21:45:29.410001       1 azuredisk.go:188] DisableAvailabilitySetNodes for controller is set as false while current VMType is vmss
```

What's weird is that I know that it's not a VMSS, so I'm not sure what this information is based on.

**Comment by andyzhangx** [comment]
are you able to set `vmType: standard` in azure.json, I think that would solve the issue.

**Comment by gnadaban** [comment]
I'll need to look into it a bit more, we're using `cluster-api` so the Azure config is generated.

**Comment by andyzhangx** [comment]
@gnadaban if you try with latest v1.18.0 release, you could set `--vm-type=standard` in azure disk controller config, I think that would solve the issue.

https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/fa3afcd4355aea94e9c413f72da615bb44a3bd5b/charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml#L145-L150

**Comment by gnadaban** [comment]
Thanks @andyzhangx , I tried with 1.18 and `--vm-type=standard` and with both `true/false` values of `--disable-avset-nodes` and I'm _still_ getting errors about the node not being a vmss one.

```
azure_controller_common.go:441] error of getting data disks for node <redacted>: not a vmss instance
controllerserver.go:381] Trying to attach volume /subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/pvc-da9c479b-f82a-405b-a52c-6774cd11fa18 to node <redacted>
azure_controller_common.go:466] error of getting data disks for node <redacted>: not a vmss instance
controllerserver.go:402] Attach volume /subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/pvc-da9c479b-f82a-405b-a52c-6774cd11fa18 to instance <redacted> failed with not a vmss instance
```

**Comment by gnadaban** [comment]
Update: I've tried leaving the `vmType` override with the default empty setting and apparently it works! :)
I'll confirm once more, but it's looking good! 

On another note, I am confused why I was getting the errors otherwise.

**Comment by andyzhangx** [comment]
@gnadaban there are two controller replicas, after the change, you need to delete the two replica pods manually, otherwise the setting would not take effect.

**Comment by gnadaban** [comment]
Hey @andyzhangx , I think we can close this one, thanks for all your help! :)
